export const LOG_ERROR = 'LOG_ERROR'
export const SAVE_USER = 'SAVE_USER'
export const SAVE_USER_NOTES = 'SAVE_USER_NOTES'

export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION'
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION'
